# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~

            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        user_db:
            entity: { class: Acme\UserBundle\Entity\Usuarios, property: usuario }


    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false